sonar.organization=signalsafesoftware
sonar.projectKey=signalsafe-package-tree-spec-learner-react
sonar.projectName=@signalsafe/tree-spec-learner-react
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx,tests/**/*.spec.ts,tests/**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
